create or replace PACKAGE RETURN_CODE_CONSTANTS
AS

CODE_SUCCESS     CONSTANT NUMBER := 1;
CODE_EXPECTED_EVENT CONSTANT NUMBER := 0;
CODE_FAILURE   CONSTANT NUMBER := -1;

-- Use this with CODE_SUCCESS
SUCCESS          CONSTANT VARCHAR2(30) := 'SUCCESS';

-- Use these with CODE_EXPECTED_EVENT
EVENT_NO_DATA_FOUND      CONSTANT VARCHAR2(30) := 'NO_DATA_FOUND';
EVENT_DUP_VAL_ON_INDEX     CONSTANT VARCHAR2(30) := 'DUP_VAL_ON_INDEX';
EVENT_PARENT_KEY_NOT_FOUND    CONSTANT VARCHAR2(30) := 'CCC_PARENT_KEY_NOT_FOUND';
EVENT_CHILD_RECORD_FOUND    CONSTANT VARCHAR2(30) := 'CCC_CHILD_RECORD_FOUND';
EVENT_CHILD_RECORD_NOT_FOUND   CONSTANT VARCHAR2(30) := 'CCC_CHILD_RECORD_NOT_FOUND';
EVENT_VERSION_MISMATCH     CONSTANT VARCHAR2(30) := 'CCC_VERSION_MISMATCH';
EVENT_INAPPROPRIATE_STATE   CONSTANT VARCHAR2(30) := 'CCC_INAPPROPRIATE_STATE';
EVENT_CLIENT_EXPECTED_RESULT  CONSTANT VARCHAR2(30) := 'CLIENT_EXPECTED_RESULT';

-- Use these with CODE_FAILURE
FAILURE_ORACLE_ERROR    CONSTANT VARCHAR2(30) := 'ORACLEERROR';
FAILURE_TOO_MANY_ROWS    CONSTANT VARCHAR2(30) := 'TOO_MANY_ROWS';
FAILURE_NOT_IMPLEMENTED    CONSTANT VARCHAR2(30) := 'NOT_IMPLEMENTED';

END RETURN_CODE_CONSTANTS;
/