
package com.copyright.ccc.business.services;

public enum LangEnum {
	
	ALL("0", "all"),
	ENGLISH("1", "English"),
	ABKHAZ("2", "Abkhaz"),
	ACHINESE("3", "Achinese"),
	ACOLI("4", "Acoli"),
	ADANGME("5", "Adangme"),
	ADYGEI("6", "Adygei"),
	AFAR("7", "Afar"),
	AFRIHILI("8", "Afrihili"),
	AFRIKAANS("9", "Afrikaans"),
	AINU("10", "Ainu"),
	AKAN("11", "Akan"),
	AKKADIAN("12", "Akkadian"),
	ALBANIAN("13", "Albanian"),
	ALEUT("14", "Aleut"),
	ALGONQUIN("15", "Algonquin"),
	ALTAIC("16", "Altaic"),
	AMHARIC("17", "Amharic"),
	ANGIKA("18", "Angika"),
	APACHE("19", "Apache"),
	ARABIC("20", "Arabic"),
	ARAGONESESPANISH("21", "Aragonese Spanish"),
	ARAMAIC("22", "Aramaic"),
	ARANES("23", "Aranes"),
	ARAPAHO("24", "Arapaho"),
	ARAWAK("25", "Arawak"),
	ARMENIAN("26", "Armenian"),
	AROMANIAN("27", "Aromanian"),
	ARTIFICIALOTHER("28", "Artificial (Other)"),
	ASSAMESE("29", "Assamese"),
	ATHAPASCAN("30", "Athapascan (Other)"),
	ATURIAN("31", "Aturian"),
	AUSTRALIANLANGUAGES("32", "Australian Languages"),
	AUSTRONESIAN("33", "Austronesian (Other)"),
	AVARIC("34", "Avaric"),
	AVESTAN("35", "Avestan"),
	AWADHI("36", "Awadhi"),
	AYMARA("37", "Aymara"),
	AZERBAIJANI("38", "Azerbaijani"),
	BALINESE("39", "Balinese"),
	BALTIC("40", "Baltic (Other)"),
	BALUCHI("41", "Baluchi"),
	BAMBARA("42", "Bambara"),
	BAMILEKELANGUAGES("43", "Bamileke Languages"),
	BANDALANUGAGES("44", "Banda Lanugages"),
	BANTU("45", "Bantu"),
	BASA("46", "Basa"),
	BASHKIR("47", "Bashkir"),
	BASQUE("48", "Basque"),
	BATAKLANGUAGES("49", "Batak Languages"),
	BEJA("50", "Beja"),
	BELARUSIAN("51", "Belarusian"),
	BEMBA("52", "Bemba"),
	BENGALI("53", "Bengali"),
	BERBER("54", "Berber (Other)"),
	BHOJPURI("55", "Bhojpuri"),
	BIHARI("56", "Bihari"),
	BIKOL("57", "Bikol"),
	BILIN("58", "Bilin"),
	BINI("59", "Bini"),
	BISLAMA("60", "Bislama"),
	BOSNIAN("61", "Bosnian"),
	BRAJ("62", "Braj"),
	BRETON("63", "Breton"),
	BUGIS("64", "Bugis"),
	BULGARIAN("65", "Bulgarian"),
	BURIAT("66", "Buriat"),
	BURMESE("67", "Burmese"),
	CADDO("68", "Caddo"),
	CATALAN("69", "Catalan"),
	CAUCASIAN("70", "Caucasian"),
	CEBUANO("71", "Cebuano"),
	CELTIC("72", "Celtic (Other)"),
	CENTRALAMERICANINDIAN("73", "Central American Indian (Other)"),
	CENTRALKHMER("74", "Central Khmer"),
	CHAGATAI("75", "Chagatai"),
	CHAMICLANGUAGES("76", "Chamic Languages"),
	CHAMORRO("77", "Chamorro"),
	CHECHEN("78", "Chechen"),
	CHEROKEE("79", "Cherokee"),
	CHEYENNE("80", "Cheyenne"),
	CHIBCHA("81", "Chibcha"),
	CHICHEWA("82", "Chichewa"),
	CHINESE("83", "Chinese"),
	CHINOOKJARGON("84", "Chinook Jargon"),
	CHIPEWYAN("85", "Chipewyan"),
	CHOCTAW("86", "Choctaw"),
	CHURCHSLAVIC("87", "Church Slavic"),
	CHUVASH("88", "Chuvash"),
	CLASSICALNEWARI("89", "Classical Newari"),
	CLASSICALSYRIAC("90", "Classical Syriac"),
	COPTIC("91", "Coptic"),
	CORNISH("92", "Cornish"),
	CORSICAN("93", "Corsican"),
	CREE("94", "Cree"),
	CREEK("95", "Creek"),
	CREOLESANDPIDGINS("96", "Creoles and Pidgins (Other)"),
	CREOLESANDPIDGINSENGLISHBASED("97", "Creoles and Pidgins, English-based (Other)"),
	CREOLESANDPIDGINSFRENCHBASED("98", "Creoles and Pidgins, French-based (Other)"),
	CREOLESANDPIDGINSPORTUGUESEBASED("99", "Creoles and Pidgins, Portuguese-based (Other)"),
	CRIMEANTURKISH("100", "Crimean Turkish"),
	CROATIAN("101", "Croatian"),
	CUSHITIC("102", "Cushitic (Other)"),
	CZECH("103", "Czech"),
	DAKOTA("104", "Dakota"),
	DANISH("105", "Danish"),
	DARGWA("106", "Dargwa"),
	DELAWARE("107", "Delaware"),
	DINKA("108", "Dinka"),
	DIVEHI("109", "Divehi"),
	DOGRI("110", "Dogri"),
	DOGRIB("111", "Dogrib"),
	DRAVIDIAN("112", "Dravidian (Other)"),
	DUALA("113", "Duala"),
	DUTCH("114", "Dutch"),
	DUTCHMIDDLECA("115", "Dutch, Middle (ca. 1050-1350)"),
	DYULA("116", "Dyula"),
	DZONGKHA("117", "Dzongkha"),
	EASTERNFRISIAN("118", "Eastern Frisian"),
	EFIK("119", "Efik"),
	EGYPTIAN("120", "Egyptian"),
	EKAJUK("121", "Ekajuk"),
	ELAMITE("122", "Elamite"),
	ENGLISHMIDDLE("123", "English, Middle (1100-1500)"),
	ERZYA("124", "Erzya"),
	ESKIMO("125", "Eskimo"),
	ESPERANTO("126", "Esperanto"),
	ESTONIAN("127", "Estonian"),
	ETHIOPIC("128", "Ethiopic"),
	EWE("129", "Ewe"),
	EWONDO("130", "Ewondo"),
	FANG("131", "Fang"),
	FANTI("132", "Fanti"),
	FAROESE("133", "Faroese"),
	FIJIAN("134", "Fijian"),
	FILIPINOPILIPINO("135", "Filipino; Pilipino"),
	FINNISH("136", "Finnish"),
	FINNOUGRIAN("137", "Finno-Ugrian (Other)"),
	FON("138", "Fon"),
	FRENCH("139", "French"),
	FRENCHMIDDLE("140", "French, Middle (ca. 1400-1600)"),
	FRENCHOLD("141", "French, Old (ca. 842-1400)"),
	FRISIAN("142", "Frisian"),
	FRIULIAN("143", "Friulian"),
	FULA("144", "Fula"),
	GA("145", "Ga"),
	GALIBICARIB("146", "Galibi Carib"),
	GALICIAN("147", "Galician"),
	GANDA("148", "Ganda"),
	GAYO("149", "Gayo"),
	GBAYA("150", "Gbaya"),
	GEORGIAN("151", "Georgian"),
	GERMAN("152", "German"),
	GERMANMIDDLEHIGH("153", "German, Middle High"),
	GERMANOLDHIGH("154", "German, Old High (ca. 750-1050)"),
	GERMANIC("155", "Germanic (Other)"),
	GILBERTESE("156", "Gilbertese"),
	GONDI("157", "Gondi"),
	GORONTALO("158", "Gorontalo"),
	GOTHIC("159", "Gothic"),
	GREBO("160", "Grebo"),
	GREEK("161", "Greek"),
	GREEKANCIENT("162", "Greek, Ancient (to 1453)"),
	GUARANI("163", "Guarani"),
	GUJARATI("164", "Gujarati"),
	GWICH("165", "Gwich'in"),
	HAIDA("166", "Haida"),
	HAITIANFRENCHCREOLE("167", "Haitian French Creole"),
	HAUSA("168", "Hausa"),
	HAWAIIAN("169", "Hawaiian"),
	HEBREW("170", "Hebrew"),
	HERERO("171", "Herero"),
	HILIGAYNON("172", "Hiligaynon"),
	HIMACHALI("173", "Himachali"),
	HINDI("174", "Hindi"),
	HIRIMOTU("175", "Hiri Motu"),
	HITTITE("176", "Hittite"),
	HMONG("177", "Hmong"),
	HUNGARIAN("178", "Hungarian"),
	HUPA("179", "Hupa"),
	IBAN("180", "Iban"),
	ICELANDIC("181", "Icelandic"),
	IDO("182", "Ido"),
	IGBO("183", "Igbo"),
	IJOLANGUAGES("184", "Ijo languages"),
	ILOKO("185", "Iloko"),
	INARISAMI("186", "Inari Sami"),
	INDIC("187", "Indic"),
	INDOEUROPEAN("188", "Indo-European (Other)"),
	INDONESIAN("189", "Indonesian"),
	INGUSH("190", "Ingush"),
	INTERLINGUA("191", "Interlingua"),
	INTERLINGUE("192", "Interlingue"),
	INUKTITUT("193", "Inuktitut"),
	INUPIAQ("194", "Inupiaq"),
	IRANIAN("195", "Iranian"),
	IRISH("196", "Irish"),
	IRISHMIDDLE("197", "Irish, Middle (ca. 1100-1550)"),
	IRISHOLD("198", "Irish, Old (to 1100)"),
	IROQUOIAN("199", "Iroquoian (Other)"),
	ITALIAN("200", "Italian"),
	JAPANESE("201", "Japanese"),
	JAVANESE("202", "Javanese"),
	JUDEOARABIC("203", "Judeo-Arabic"),
	JUDEOPERSIAN("204", "Judeo-Persian"),
	KABARDIAN("205", "Kabardian"),
	KABYLE("206", "Kabyle"),
	KACHIN("207", "Kachin"),
	KALATDLISUT("208", "Kalatdlisut"),
	KALMYK("209", "Kalmyk"),
	KAMBA("210", "Kamba"),
	KANNADA("211", "Kannada"),
	KANURI("212", "Kanuri"),
	KARAKALPAK("213", "Kara-Kalpak"),
	KARACHAYBALKAR("214", "Karachay-Balkar"),
	KARELIAN("215", "Karelian"),
	KARENLANGUAGES("216", "Karen languages"),
	KASHMIRI("217", "Kashmiri"),
	KASHUBIAN("218", "Kashubian"),
	KAWI("219", "Kawi"),
	KAZAKH("220", "Kazakh"),
	KHASI("221", "Khasi"),
	KHOISAN("222", "Khoisan (Other)"),
	KHOTANESE("223", "Khotanese"),
	KIKUYU("224", "Kikuyu"),
	KIMBUNDU("225", "Kimbundu"),
	KINYARWANDA("226", "Kinyarwanda"),
	KIRGHIZ("227", "Kirghiz"),
	KLINGON("228", "Klingon"),
	KOMI("229", "Komi"),
	KONGO("230", "Kongo"),
	KONKANI("231", "Konkani"),
	KOREAN("232", "Korean"),
	KPELLE("233", "Kpelle"),
	KRULANGUAGES("234", "Kru languages"),
	KUANYAMA("235", "Kuanyama"),
	KUMYK("236", "Kumyk"),
	KURDISH("237", "Kurdish"),
	KURUKH("238", "Kurukh"),
	KUSAIE("239", "Kusaie"),
	KUTENAI("240", "Kutenai"),
	LADINO("241", "Ladino"),
	LAHNDA("242", "Lahnda"),
	LAMDA("243", "Lamda"),
	LANDDAYAKLANGUAGES("244", "Land Dayak languages"),
	LAO("245", "Lao"),
	LATIN("246", "Latin"),
	LATVIAN("247", "Latvian"),
	LEZGIAN("248", "Lezgian"),
	LIMBURGISH("249", "Limburgish"),
	LINGALA("250", "Lingala"),
	LITHUANIAN("251", "Lithuanian"),
	LOJBAN("252", "Lojban"),
	LOWGERMAN("253", "Low German"),
	LOWERSORBIAN("254", "Lower Sorbian"),
	LOZI("255", "Lozi"),
	LUBAKATANGA("256", "Luba-Katanga"),
	LUBALULUA("257", "Luba-Lulua"),
	LUISE("258", "Luise?o"),
	LULESAMI("259", "Lule Sami"),
	LUNDA("260", "Lunda"),
	LUOKENYAANDTANZANIA("261", "Luo (Kenya and Tanzania)"),
	LUSHAI("262", "Lushai"),
	LUXEMBOURGISH("263", "Luxembourgish"),
	MACEDONIAN("264", "Macedonian"),
	MADURESE("265", "Madurese"),
	MAGAHI("266", "Magahi"),
	MAITHILI("267", "Maithili"),
	MAKASAR("268", "Makasar"),
	MALAGASY("269", "Malagasy"),
	MALAY("270", "Malay"),
	MALAYALAM("271", "Malayalam"),
	MALTESE("272", "Maltese"),
	MANCHU("273", "Manchu"),
	MANDAR("274", "Mandar"),
	MANDINGO("275", "Mandingo"),
	MANIPURI("276", "Manipuri"),
	MANOBOLANGUAGES("277", "Manobo languages"),
	MANX("278", "Manx"),
	MAORI("279", "Maori"),
	MAPUDUNGUN("280", "Mapudungun"),
	MARATHI("281", "Marathi"),
	MARI("282", "Mari"),
	MARSHALL("283", "Marshall"),
	MARWARI("284", "Marwari"),
	MASAI("285", "Masai"),
	MAYANLANGUAGES("286", "Mayan languages"),
	MENDE("287", "Mende"),
	MIKMAQ("288", "Mi'kmaq"),
	MINANGKABAU("289", "Minangkabau"),
	MIRANDESE("290", "Mirandese"),
	MISCELLANEOUSLANGUAGES("291", "Miscellaneous languages"),
	MOHAWK("292", "Mohawk"),
	MOKSHA("293", "Moksha"),
	MOLDAVIAN("294", "Moldavian"),
	MONKHMER("295", "Mon-Khmer (Other)"),
	MONGONKUNDU("296", "Mongo-Nkundu"),
	MONGOLIAN("297", "Mongolian"),
	MOORE("298", "Moore"),
	MULTIPLELANGUAGES("299", "Multiple languages"),
	MUNDA("300", "Munda (Other)"),
	NKO("301", "N'Ko"),
	NAHUATLLANGUAGES("302", "Nahuatl languages"),
	NAURU("303", "Nauru"),
	NAVAJO("304", "Navajo"),
	NDEBELENORTH("305", "Ndebele, North"),
	NDEBELESOUTH("306", "Ndebele, South"),
	NDONGA("307", "Ndonga"),
	NEAPOLITAN("308", "Neapolitan"),
	NEPALI("309", "Nepali"),
	NEWARI("310", "Newari"),
	NIAS("311", "Nias"),
	NIGERKORDOFANIAN("312", "Niger-Kordofanian (Other)"),
	NILOSAHARAN("313", "Nilo-Saharan"),
	NIUEAN("314", "Niuean"),
	NOGAI("315", "Nogai"),
	NORTHAMERICANINDIAN("316", "North American Indian (Other)"),
	NORTHERNFRISIAN("317", "Northern Frisian"),
	NORTHERNSAMI("318", "Northern Sami"),
	NORWEGIAN("319", "Norwegian"),
	NORWEGIANBOKMAL("320", "Norwegian Bokmal"),
	NORWEGIANNYNORSK("321", "Norwegian Nynorsk"),
	NUBIAN("322", "Nubian"),
	NYAMWEZI("323", "Nyamwezi"),
	NYANKOLE("324", "Nyankole"),
	NYOROGROUP("325", "Nyoro Group"),
	NZIMA("326", "Nzima"),
	OCCITAN("327", "Occitan (post-1500); Provencal"),
	OJIBWA("328", "Ojibwa"),
	OLDENGLISH("329", "Old English"),
	OLDNORSE("330", "Old Norse"),
	OLDPERSIAN("331", "Old Persian (ca. 600-400 B.C.)"),
	ORIYA("332", "Oriya"),
	OROMO("333", "Oromo"),
	OSAGE("334", "Osage"),
	OSSETIC("335", "Ossetic"),
	OTOMIANLANGUAGES("336", "Otomian languages"),
	PAHLAVI("337", "Pahlavi"),
	PALAUAN("338", "Palauan"),
	PALI("339", "Pali"),
	PAMPANGA("340", "Pampanga"),
	PANGASINAN("341", "Pangasinan"),
	PANJABI("342", "Panjabi"),
	PAPIAMENTO("343", "Papiamento"),
	PAPUAN("344", "Papuan (Other)"),
	PEDI("345", "Pedi"),
	PERSIAN("346", "Persian"),
	PHILLIPINE("347", "Phillipine (Other)"),
	PHOENICIAN("348", "Phoenician"),
	POLISH("349", "Polish"),
	PONAPE("350", "Ponape"),
	PORTUGUESE("351", "Portuguese"),
	PRAKRITLANGUAGES("352", "Prakrit languages"),
	PROVEN("353", "Proven? (to 1500)"),
	PUSHTO("354", "Pushto"),
	QUECHUA("355", "Quechua"),
	RAJASTHANI("356", "Rajasthani"),
	RAPANUI("357", "Rapanui"),
	RAROTONGAN("358", "Rarotongan"),
	ROMANCE("359", "Romance (Other)"),
	ROMANIAN("360", "Romanian"),
	ROMANSH("361", "Romansh"),
	ROMANY("362", "Romany"),
	RUNDI("363", "Rundi"),
	RUSSIAN("364", "Russian"),
	SALISHANLANGUAGES("365", "Salishan languages"),
	SAMARITANARAMAIC("366", "Samaritan Aramaic"),
	SAMILANGUAGES("367", "Sami languages"),
	SAMOAN("368", "Samoan"),
	SANDAWE("369", "Sandawe"),
	SANGO("370", "Sango"),
	SANSKRIT("371", "Sanskrit"),
	SANTALI("372", "Santali"),
	SARDINIAN("373", "Sardinian"),
	SASAK("374", "Sasak"),
	SCOTS("375", "Scots"),
	SCOTTISHGAELIC("376", "Scottish Gaelic"),
	SELKUP("377", "Selkup"),
	SEMITIC("378", "Semitic (Other)"),
	SERBIAN("379", "Serbian"),
	SERER("380", "Serer"),
	SHAN("381", "Shan"),
	SHONA("382", "Shona"),
	SICHUANYI("383", "Sichuan Yi"),
	SICILIAN("384", "Sicilian"),
	SIDAMO("385", "Sidamo"),
	SIGNLANGUAGES("386", "Sign languages"),
	SIKSIKA("387", "Siksika"),
	SINDHI("388", "Sindhi"),
	SINHALESE("389", "Sinhalese"),
	SINOTIBETAN("390", "Sino-Tibetan (Other)"),
	SIOUAN("391", "Siouan"),
	SKOLTSAMI("392", "Skolt Sami"),
	SLAVE("393", "Slave"),
	SLAVIC("394", "Slavic"),
	SLOVAK("395", "Slovak"),
	SLOVENIAN("396", "Slovenian"),
	SOGDIAN("397", "Sogdian"),
	SOMALI("398", "Somali"),
	SONGHAI("399", "Songhai"),
	SONINKE("400", "Soninke"),
	SORBIANLANGUAGES("401", "Sorbian languages"),
	SOTHO("402", "Sotho"),
	SOUTHAMERICANINDIAN("403", "South American Indian (Other)"),
	SOUTHERNALTAI("404", "Southern Altai"),
	SOUTHERNSAMI("405", "Southern Sami"),
	SPANISH("406", "Spanish"),
	SRANANTONGO("407", "Sranan Tongo"),
	SUDANESE("408", "Sudanese"),
	SUKUMA("409", "Sukuma"),
	SUMERIAN("410", "Sumerian"),
	SUSU("411", "Susu"),
	SWAHILI("412", "Swahili"),
	SWAZI("413", "Swazi"),
	SWEDISH("414", "Swedish"),
	SWISSGERMAN("415", "Swiss German"),
	SYRIAC("416", "Syriac"),
	TAGALOG("417", "Tagalog"),
	TAHITIAN("418", "Tahitian"),
	TAI("419", "Tai"),
	TAJIK("420", "Tajik"),
	TAMASHEK("421", "Tamashek"),
	TAMIL("422", "Tamil"),
	TATAR("423", "Tatar"),
	TELUGU("424", "Telugu"),
	TEMNE("425", "Temne"),
	TERENA("426", "Terena"),
	TETUM("427", "Tetum"),
	THAI("428", "Thai"),
	TIBETAN("429", "Tibetan"),
	TIGRE("430", "Tigre"),
	TIGRINYA("431", "Tigrinya"),
	TIV("432", "Tiv"),
	TLINGIT("433", "Tlingit"),
	TOKPISIN("434", "Tok Pisin"),
	TOKELAUAN("435", "Tokelauan"),
	TONGA("436", "Tonga (Nyasa)"),
	TONGAN("437", "Tongan"),
	TRUK("438", "Truk"),
	TSIMSHIAN("439", "Tsimshian"),
	TSONGA("440", "Tsonga"),
	TSWANA("441", "Tswana"),
	TUMBUKA("442", "Tumbuka"),
	TUPILANGUAGES("443", "Tupi languages"),
	TURKISH("444", "Turkish"),
	TURKISHOTTOMAN("445", "Turkish, Ottoman"),
	TURKMEN("446", "Turkmen"),
	TUVALUAN("447", "Tuvaluan"),
	TUVINIAN("448", "Tuvinian"),
	TWI("449", "Twi"),
	UDMURT("450", "Udmurt"),
	UGARITIC("451", "Ugaritic"),
	UIGHUR("452", "Uighur"),
	UKRAINIAN("453", "Ukrainian"),
	UMBUNDU("454", "Umbundu"),
	UPPERSORBIAN("455", "Upper Sorbian"),
	URDU("456", "Urdu"),
	UZBEK("457", "Uzbek"),
	VAI("458", "Vai"),
	VALENCIAN("459", "Valencian"),
	VENDA("460", "Venda"),
	VIETNAMESE("461", "Vietnamese"),
	VOLAPK("462", "Volap?k"),
	VOTIC("463", "Votic"),
	WAKASHANLANGUAGES("464", "Wakashan languages"),
	WALAMO("465", "Walamo"),
	WALLOON("466", "Walloon"),
	WARAY("467", "Waray"),
	WASHO("468", "Washo"),
	WELSH("469", "Welsh"),
	WOLOF("470", "Wolof"),
	XHOSA("471", "Xhosa"),
	YAKUT("472", "Yakut"),
	YAO("473", "Yao"),
	YAPESE("474", "Yapese"),
	YIDDISH("475", "Yiddish"),
	YORUBA("476", "Yoruba"),
	YUPIKLANGUAGES("477", "Yupik languages"),
	ZANDE("478", "Zande"),
	ZAPOTEC("479", "Zapotec"),
	ZAZA("480", "Zaza"),
	ZENAGA("481", "Zenaga"),
	ZHUANG("482", "Zhuang"),
	ZULU("483", "Zulu"),
	ZUNI("484", "Zuni");
	
	
	String langCode;
	String langName;
	
	
	private LangEnum(String countryKey, String countryName) {
		this.langCode = countryKey;
		this.langName = countryName;
	}
	
	public static String getLangCodeForName( String name ) {
		for ( LangEnum ce : LangEnum.values() ) {
			if ( name.equalsIgnoreCase(ce.getLangName())) {
				return ce.langCode;
			} 
		}
		return null;
	}
	
	public String getLangName() 
	{
		return langName;
	}
	

	/* public static ProductEnum getEnumForName( String name ) {
		for ( ProductEnum pe : ProductEnum.values() ) {
			if ( name.equalsIgnoreCase(pe.name())) {
				return pe;
			} 
		}
		return null;
	}
	
	public static ProductEnum getEnumForProductSourceKey( Long productSourceKey ) {
		for ( ProductEnum pe : ProductEnum.values() ) {
			if ( productSourceKey.equals(pe.productSourceKey)) {
				return pe;
			} 
		}
		return null;
	}
	
	public static List<LabelValueBean> getProductCodes() {
		
		List<LabelValueBean> productCodes = new ArrayList<LabelValueBean>();
		for ( ProductEnum pe : ProductEnum.values() ) {
			LabelValueBean labelValueBean = new LabelValueBean();
			labelValueBean.setLabel(pe.name());
			labelValueBean.setValue(pe.getProductSourceKey().toString());
			productCodes.add(labelValueBean);
		}
		return productCodes;
	}
	
	public static List<LabelValueBean> getAcademicProductCodes() {
		
		List<LabelValueBean> productCodes = new ArrayList<LabelValueBean>();
		for ( ProductEnum pe : ProductEnum.values() ) {
			if (pe.getIsAcademic())
			{
				LabelValueBean labelValueBean = new LabelValueBean();
				labelValueBean.setLabel(pe.name());
				labelValueBean.setValue(pe.getProductSourceKey().toString());
				productCodes.add(labelValueBean);
			}
		}
		return productCodes;
	}
	
	public static List<LabelValueBean> getNonAcademicProductCodes() {
		
		List<LabelValueBean> productCodes = new ArrayList<LabelValueBean>();
		for ( ProductEnum pe : ProductEnum.values() ) {
			if (!pe.getIsAcademic())
			{
				LabelValueBean labelValueBean = new LabelValueBean();
				labelValueBean.setLabel(pe.name());
				labelValueBean.setValue(pe.getProductSourceKey().toString());
				productCodes.add(labelValueBean);
			}
		}
		return productCodes;
	} */
	
}
