--Removed need for table.  Direct write to CCCTF.CCC_ORDER.
--
--CREATE OR REPLACE TABLE CC.CCC_ORDER_PARTNER_XREF (
--    ORDER_CONFIRM               NUMBER(38,0) PRIMARY KEY NOT NULL, 
--    PARTNER_ID                  VARCHAR2(50 BYTE) NOT NULL
--)
--TABLESPACE CC_DATA;
--
--CREATE INDEX OPX_PARTNER_ID_IDX ON CC.CCC_ORDER_PARTNER_XREF (PARTNER_ID);
--
--COMMIT;

exit;
