/*
 * WWWBuildData.java
 * Copyright (c) 2009, Copyright Clearance Center, Inc. All rights reserved.
 * ----------------------------------------------------------------------------
 * Revision History
 * 2009.05.14   tmckinney    Created.
 * ----------------------------------------------------------------------------
 */
package com.copyright.ccc.config;

import java.io.IOException;

import org.apache.log4j.Logger;

import com.copyright.base.CCCRuntimeException;
import com.copyright.base.config.AppServerConfiguration;
import com.copyright.base.config.BuildData;
import com.copyright.workbench.logging.LoggerHelper;

/**
 * Build data for copyright.com app.
 *
 * @author tmckinney
 * @version 1.0
 */
public class WWWBuildData extends BuildData
{
	private static final long serialVersionUID = 1L;
	
	//expected file name containing build data.
	private static String FILE_NAME = "www-builddata.txt";

    // Single instance of configuration information shared across 
    // the application.
    private static WWWBuildData INSTANCE;
    
    private static Logger sLogger = LoggerHelper.getLogger();
	
    /**
     * Private for non-instantiation.
     */
	private WWWBuildData() throws IOException
	{
		super(WWWBuildData.class, FILE_NAME);
	}

    /**
     * Client code should use this method to get a handle on the 
     * <code>WWWBuildData</code> object.
     */
    public static synchronized WWWBuildData getInstance()
    {
        if ( INSTANCE == null )
        {
            try
            {
            	INSTANCE = new WWWBuildData();
            }
            catch ( IOException ioe )
            {
                String msg = "IOException while instantiating WWWBuildData";
                throw new CCCRuntimeException( msg, ioe );
            }
            catch ( NullPointerException npe )
            {
            	if ( AppServerConfiguration.isLOCAL() )
            	{
            		// Builds via Eclipse will not have the build data file that is 
            		// generated by ccc-ant.  If this is a local build, we consider
            		// this to be acceptable.  [dstine 3/2/10]
            		
            		sLogger.debug( "Cannot load " + FILE_NAME + " (generated by ccc-ant)" );
            	}
            	else
            	{
            		throw npe;
            	}
            }
        }
        
        return INSTANCE;
    }
}
