SET ECHO ON

CREATE TABLE CCC_USER
(
    USER_ID NUMBER(38,0) NOT NULL,
    USER_TYPE VARCHAR2(15) DEFAULT 'CUST',
    PARTY_ID NUMBER(38,0) NOT NULL,
    USER_IDENTIFIER VARCHAR2(100),
    OID_PK VARCHAR2(300),
    VERSION NUMBER(38,0) DEFAULT 1 NOT NULL,
    CRE_USER NUMBER(38,0) NOT NULL,
    CRE_DTM TIMESTAMP (6) NOT NULL,
    UPD_USER NUMBER(38,0),
    UPD_DTM TIMESTAMP(6)
)
TABLESPACE  CC_DATA;


CREATE TABLE CCC_USER_REQUEST_CLIENT(
    USER_REQUEST_CLIENT_ID	NUMBER(38, 0) NOT NULL,
    USER_ID			NUMBER(38, 0) NOT NULL,
    AU_ID			VARCHAR2(40) NOT NULL,
    LAST_SESSION_START		TIMESTAMP(6)  DEFAULT SYSDATE NOT NULL,
    LAST_CART_ID		NUMBER(38, 0),
    ALWAYS_INVOICE		CHAR(1) DEFAULT 'N' NOT NULL,
    IS_ANONYMOUS		CHAR(1) DEFAULT 'Y' NOT NULL,
    SP_ALL			CHAR(1) DEFAULT 'Y' NOT NULL,
    SP_PHOTOCOPY_ACADEMIC       CHAR(1) DEFAULT 'N' NOT NULL,
    SP_SHARE_ILL        CHAR(1) DEFAULT 'N' NOT NULL,
    SP_PHOTOCOPY_GENERAL        CHAR(1) DEFAULT 'N' NOT NULL,
    SP_COURSEPACK               CHAR(1) DEFAULT 'N' NOT NULL,
    SP_DIGITAL                  CHAR(1) DEFAULT 'N' NOT NULL,
    SP_REPUBLISH                CHAR(1) DEFAULT 'N' NOT NULL,
    SP_BUSINESS_PHOTOCOPY       CHAR(1) DEFAULT 'N' NOT NULL,
    SP_BUSINESS_DIGITAL_INTERNAL CHAR(1) DEFAULT 'N' NOT NULL,
    SP_ACADEMIC_LICENSE         CHAR(1) DEFAULT 'N' NOT NULL,
	SP_RIGHTSLINK_REPRINT       CHAR(1) DEFAULT 'N' NOT NULL,
	SP_RIGHTSLINK_DIGITAL       CHAR(1) DEFAULT 'N' NOT NULL,
    VERSION			NUMBER(38, 0) NOT NULL,
    CRE_USER			NUMBER(38, 0) NOT NULL,
    CRE_DTM			TIMESTAMP(6)  NOT NULL,
    UPD_USER			NUMBER(38, 0),
    UPD_DTM			TIMESTAMP(6),
    SKIP_QUICKPRICE CHAR(1) DEFAULT 'N' NOT NULL
)
TABLESPACE CC_DATA;

CREATE TABLE CCC_RLINK_PUBLISHER(
    RLINK_PUB_ID                NUMBER (15, 0) NOT NULL,
    PUB_PTY_INST                NUMBER (15, 0) NOT NULL,
    ACCOUNT_NUM                 NUMBER (15, 0) NOT NULL,
    WRK_INST                    NUMBER (15, 0),
    PUB_NAME                    VARCHAR2 (80),
    PUB_URL                     VARCHAR2 (1000),
    PERM_OPTION_DESC            VARCHAR2 (4000),
    LEARN_MORE_DESC             VARCHAR2 (4000),
    CRE_USER                    VARCHAR2 (30),
    CRE_DTM                     TIMESTAMP (6),
    UPD_USER                    VARCHAR2 (30),
    UPD_DTM                     TIMESTAMP (6)
)
TABLESPACE CC_DATA;

CREATE TABLE CCC_RLINK_PUBLISHER_DETAIL(
    RLINK_PUB_ID                NUMBER (15, 0) NOT NULL,
    PUB_PTY_INST                NUMBER (15, 0) NOT NULL,
    SUB_ACCOUNT_NUM             NUMBER (15, 0) NOT NULL,
    WRK_INST                    NUMBER (15, 0),
    CRE_USER                    VARCHAR2 (30),
    CRE_DTM                     TIMESTAMP (6),
    UPD_USER                    VARCHAR2 (30),
    UPD_DTM                     TIMESTAMP (6)
)
TABLESPACE CC_DATA;

CREATE TABLE CCC_AUTODUNNING_PARAMS(
    PRODUCT_TYPE                VARCHAR2(15 CHAR) NOT NULL,
    DAYS_PAST_DUE               NUMBER(38) NOT NULL,
    ENABLED                     NUMBER(38) DEFAULT 1 NOT NULL
)
TABLESPACE CC_DATA;

CREATE TABLE CC.CCC_ORDER_PARTNER_XREF (
    ORDER_CONFIRM               NUMBER(38,0) PRIMARY KEY NOT NULL, 
    PARTNER_ID                  VARCHAR2(50 BYTE) NOT NULL
)
TABLESPACE CC_DATA;

CREATE INDEX OPX_PARTNER_ID_IDX ON CC.CCC_ORDER_PARTNER_XREF (PARTNER_ID);

SET ECHO OFF