CREATE UNIQUE INDEX CCC_USER_REQ_AU_ID_X1 ON CCC_USER_REQUEST_CLIENT(AU_ID)
TABLESPACE CC_INDEX
;

CREATE UNIQUE INDEX CCC_USER_REQ_USER_AU_ID_X1 ON CCC_USER_REQUEST_CLIENT(USER_ID,AU_ID)
TABLESPACE CC_INDEX
;

CREATE UNIQUE INDEX CCC_USER_LOWER_USR_IDENT_IX on CCC_USER (LOWER(USER_IDENTIFIER))
TABLESPACE CC_INDEX
;

CREATE UNIQUE INDEX CCC_USER_LOWER_USR_IDENT_IX2 ON CCC_USER ("USER_IDENTIFIER" ASC)
TABLESPACE  cc_index
;


CREATE UNIQUE INDEX CCC_RLINK_PUB_PTY_INST_IDX ON CCC_RLINK_PUBLISHER(PUB_PTY_INST)
TABLESPACE  cc_index
;

CREATE UNIQUE INDEX CCC_RLINK_DET_PUB_PTY_INST_IDX ON CCC_RLINK_PUBLISHER_DETAIL(PUB_PTY_INST)
TABLESPACE  cc_index
;


CREATE INDEX IPL_LOGGED_ON_IDX ON CCC_INV_PMT_LOG(LOGGED_ON)
TABLESPACE  cc_index
;

CREATE INDEX IPL_ACCOUNT_NUMBER_IDX ON CCC_INV_PMT_LOG(ACCOUNT_NUMBER)
TABLESPACE  cc_index
;

CREATE INDEX IPL_RECEIPT_NUMBER ON CCC_INV_PMT_LOG(RECEIPT_NUMBER)
TABLESPACE  cc_index
;

CREATE INDEX OPX_PARTNER_ID_IDX ON CCC_ORDER_PARTNER_XREF(PARTNER_ID)
TABLESPACE CC_INDEX
;
