<%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean"%>
<%@ page errorPage="/jspError.do" %>

<META name="description" content="General Terms and Conditions of The Academic Pay-Per-Use Services.">
<META name="author" content="Copyright Clearance Center">
<META name="keywords" content="Academic Pay-Per-Use Services, APS, ECCS, Terms and Conditions, Copyright Clearance Center, CCC, Order Confirmation, Grant of Permissions, Grant of Permissions, General Terms and Conditions, LIMITATION OF LIABILITY">
<META name="rating" content="general">

<div>
<b>Terms and Conditions for Permission Categories:  "Use in Electronic Course Materials"</b> 
<p>Licenses are granted by Copyright Clearance Center, Inc. ("CCC"), as agent for the rightsholder(s) identified on the Order Confirmation (the "Rightsholder(s)"). User shall be deemed to have accepted and agreed to all of these terms and conditions if User uses the Work under this license in any fashion.</p>
<p>1. Nature and Form of Program. The license, created by the exchange of an Order Confirmation (and/or any invoice) and payment by User of the full amount set forth on the Order Confirmation (and/or invoice), provides for participation by User in CCC's electronic course content service which includes:</p> 
<p>(a) The selection of the pay-per-use permission type "posting e-reserves, course management systems, e-coursepacks" for text-based content, which grants authorizations to import requested material in electronic format, and to allow electronic access to this material to members of a designated college or university class, under the direction of an instructor designated by the college or university, accessible only by electronic control (e.g., password);</p> 
<p>(b) The selection of the pay-per-use permission type "posting e-reserves, course management systems, e-coursepacks" for material consisting of photographs or other still images not embedded in text, which grants not only the authorizations described in Paragraph 1(a) above, but also the following authorization:  to include the requested material in course materials for use consistent with Paragraph 1(a) above, including any necessary resizing, reformatting or modification of the resolution of such requested material (provided that such modification does not alter the underlying editorial content or meaning of the requested material, and provided that the resulting modified content is used solely within the scope of, and in a manner consistent with, the particular authorization described in the Order Confirmation and these terms and conditions), but not including any other form of manipulation, alteration or editing of the requested material;</p> 
<p>(c) The selection of the pay-per-use permission type "posting e-reserves, course management systems, e-coursepacks or other academic distribution" for audiovisual content, which grants not only the authorizations described in Paragraph 1(a), but also the following authorizations:  (i) to include the requested material in course materials for use consistent with Paragraph 1(a) above; (ii) to display and perform the requested material to such members of such class in the physical classroom or remotely by means of streaming media or other video formats; and (iii) to "clip" or reformat the requested material for purposes of time or content management or ease of delivery, provided that such clipping or reformatting does not alter the underlying editorial content or meaning of the requested material and that the resulting clipped or reformatted material is used solely within the scope of, and in a manner consistent with, the particular authorization described in the Order Confirmation and these terms and conditions, but (iii) no other form of manipulation, alteration or editing of the requested material.</p>
<p>No permission granted shall in any way:  (i) include any right by User to create a substantively non-identical copy of the Work or to edit or in any other way modify the Work (except by means of deleting material immediately preceding or following the entire portion of the Work copied or, in the case of Works subject to Paragraphs 1(b) or 1(c) above, as described in such Paragraphs) (ii) permit "publishing ventures" where any particular course materials would be systematically marketed at multiple institutions.</p>
<p>2. General Terms and Conditions of Electronic Course Content Service.</p> 
<p>Subject to any further limitations determined by the Rightsholder(s) (and notwithstanding any apparent contradiction in the Order Confirmation arising from data provided by User), any use authorized under the electronic course content pay-per-use service is limited as follows:</p> 
<p>(i) any permission granted shall apply to only one class (bearing a unique identifier as assigned by the institution, and thereby including all sections or other subparts of the class) at one institution;</p> 
(ii) no more than 25% of the text of a book or of the items in a published collection of essays, poems or articles may be imported; 
<p>(iii) no more than the greater of (a) 25% of the text of an issue of a journal or other periodical or (b) two articles from such an issue, may be imported;</p> 
<p>(iv) no User may sell or distribute any particular materials, whether photocopied or electronic, at more than one institution of learning;</p> 
<p>(vi) electronic access to material which is the subject of an electronic-use permission must be limited by means of electronic password, student identification or other control permitting access solely to students and instructors in the class;</p> 
<p>(vi) in the case of an electronic-use permission, User must ensure (through use of an electronic cover page or other means) that any person, upon gaining electronic access to the material which is the subject of a permission, shall see (a) a proper copyright notice, identifying the copyright rightsholder in whose name CCC has granted permission, (b) a statement to the effect that such copy was made pursuant to permission, (c) a statement identifying the class to which the material applies and notifying the reader that the material has been made available electronically solely for use in the class, and (d) a statement to the effect that the material may not be further distributed to any person outside the class, whether by copying or by transmission and whether electronically or in paper form, and User must also ensure that such cover page or other means will print out in the event that the person accessing the material chooses to print out the material or any part thereof; and</p> 
<p>(vii) any permission granted shall expire at the end of the class and, absent some other form of authorization, User is thereupon required to delete the applicable material from any electronic storage or to block electronic access to the applicable material.</p>
<p>3. Grant of Permissions.</p> 
<p>The Order Confirmation to which these terms and conditions apply includes information provided by User. CCC will not accept any order form that does not include all information identified therein as "required". The Order Confirmation notifies User whether or not a requested permission has been granted, the total fee due (if any), and any limitations imposed by the Rightsholder(s) on that permission and, unless User notifies CCC within ten (10) days of the Order Confirmation of its intention to decline any particular permission, User shall pay the amount due as set forth in the notification and shall be bound by any such limitation. Any act by User that involves reproduction or other use beyond that set forth in the notification shall be deemed in its entirety to be an unauthorized use of the material. Uses of separate portions of a Work, even if they are to be included in the same  course material or the same university or college class, require separate permissions under the electronic course content pay-per-use service.</p> 






<p>4. Payment for Permissions.</p>
<p>User shall pay to CCC the amount set forth in the Order Confirmation in full payment for any permission set forth therein (which will include both the amount due to the Rightsholder and the service fee payable to CCC), within the time set forth therein. In the event of a failure by User to pay any such amount by the due date, the applicable permission shall be null and void.</p>
 <p>5. Term.</p>
<p>Unless otherwise provided in the Order Confirmation, any grant of rights to User is "one-time", is non-exclusive and non-transferable and is limited to use completed no later than the end of the academic term (or analogous period) as to which any particular permission is granted.</p>
<p>6. Copyright.</p> 
<p>User acknowledges that the holders of copyright rights have complete discretion under the United States Copyright Act, 17 United States Code, whether to grant any permission, and whether to place any limitations on any grant, and that CCC has no right to supersede or to modify any such discretionary act by a Rightsholder. As between Rightsholder(s) and User, all Works and all rights therein, including copyright rights, remain the sole and exclusive property of the Rightsholder(s). The license granted hereunder includes only those rights expressly set forth in the Order Confirmation and in these terms and conditions, and conveys no other rights in the Work(s) to User.</p> 
<p>7. <b>LIMITATION OF LIABILITY OF CCC AND RIGHTSHOLDER(S), AND INDEMNITY BY USER.</b></p>
<p>(a)	UNDER NO CIRCUMSTANCES WILL CCC OR THE RIGHTSHOLDER(S) BE LIABLE FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES (INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF BUSINESS PROFITS OR INFORMATION, OR FOR BUSINESS INTERRUPTION) ARISING OUT OF THE USE OR INABILITY TO USE A WORK, EVEN IF ONE OF THEM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p> 
<p>(b)	In any event, the total liability of the Rightsholder and CCC (including their respective employees and directors) shall not exceed the total amount actually paid by User for this license. User assumes full liability for the actions and omissions of its principals, employees, agents, affiliates, successors and assigns. User hereby indemnifies and agrees to defend the Rightsholder(s) and CCC, and their respective employees and directors, against all claims, liability, damages, costs and expenses, including legal fees and expenses, arising out of any use of a Work beyond the scope of the rights granted herein, or any use of a Work which has been altered in any way by User, including claims of defamation or infringement of rights of copyright, publicity, privacy or other tangible or intangible property.</p> 
<p>8. Warranty; Disclaimers.</p> 
<p>(a)	THE WORK(S) AND RIGHT(S) ARE PROVIDED "AS IS". THE RIGHTSHOLDER(S) HAS GRANTED CCC THE RIGHT TO GRANT PERMISSION UNDER THESE PAY-PER-USE SERVICES, AND HAS WARRANTED THAT IT HAS ALL RIGHTS NECESSARY TO AUTHORIZE CCC TO ACT ON ITS BEHALF. CCC AND THE RIGHTSHOLDER DISCLAIM ALL OTHER WARRANTIES RELATING TO THE WORK(S) AND RIGHT(S), EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p> 
<p>(b)	USER ACKNOWLEDGES THAT THE RIGHTS GRANTED HEREUNDER OR UNDER ANY ORDER CONFIRMATION DO NOT INCLUDE ANY MODEL, PROPERTY OR OTHER RELEASES WHICH MAY BE NECESSARY FOR CERTAIN USES OF WORKS CONSISTING OF OR CONTAINING PHOTOGRAPHS, OTHER STILL IMAGES OR AUDIOVISUAL CONTENT. USER ACKNOWLEDGES THAT ADDITIONAL RIGHTS OR RELEASES MAY BE NECESSARY FOR CERTAIN USES OF MATERIALS WHICH INCLUDE DEPICTIONS OF PERSONS, PROPERTY OR TRADEMARKS AND THAT USER (AND NOT CCC OR ANY RIGHTSHOLDER) IS SOLELY RESPONSIBLE FOR OBTAINING ANY SUCH REQUIRED RIGHT OR RELEASE.</P>
<p>9. Books and Records; Right to Audit.</p> 
<p>As to each permission granted under the electronic course content service, User shall maintain for at least four full calendar years books and records sufficient for CCC to determine the numbers of copies made by User under such permission. CCC and any representatives it may designate shall have the right to audit such books and records at any time during User's ordinary business hours, upon two days' prior notice. If any such audit shall determine that User shall have underpaid for, or underreported, any electronic copies used by three percent (3%) or more, then User shall bear all the costs of any such audit; otherwise, CCC shall bear the costs of any such audit. Any amount determined by such audit to have been underpaid by User shall immediately be paid to CCC by User, together with interest thereon at the rate of 10% per annum from the date such amount was originally due. The provisions of this paragraph shall survive the termination of this license for any reason.</p> 
<p>10. License is Non-Transferable.</p> 
<p>The licensing transaction described in the Order Confirmation is personal to User. Therefore, User may not assign or transfer to any other person the license created by the Order Confirmation and these terms and conditions or any rights granted hereunder; provided, however, that User and its principals, employees, agents and affiliates are jointly and severally liable for the performance of all payments and other obligations hereunder. No amendment or waiver of any terms is binding unless set forth in a writing other than a standard User or CCC form and signed by the parties.</p> 
<p>11. Objection to Contrary Terms.</p>
<p>The Rightsholder(s) and CCC hereby object to any terms contained in any writing prepared by the User or its principals, employees, agents or affiliates and purporting to govern or otherwise relate to the licensing transaction described in the Order Confirmation, which terms are in any way inconsistent with any terms set forth in the Order Confirmation and/or in these terms and conditions or CCC's standard operating procedures, whether such writing is prepared prior to, simultaneously with or subsequent to the Order Confirmation, and whether such writing appears on a copy of the Order Confirmation or in a separate document.</p> 
<p>12. Breach.</p>
<p>Any failure by User to pay any amount when due, or any use by User of a Work beyond the scope of the license set forth in the Order Confirmation and/or these terms and conditions, shall be a material breach of the license created by the Order Confirmation and these terms and conditions. Any breach not cured within ten (10) days of notice thereof shall result in immediate termination of such license without further notice.</p> 
<p>13. Governing Law and Jurisdiction.</p> 
<p>The licensing transaction described in the Order Confirmation document shall be governed by and construed under the law of the State of New York, USA, without regard to the principles thereof of conflicts of law. Any case, controversy, suit, action, or proceeding arising out of, in connection with, or related to such licensing transaction shall be brought, at CCC's sole discretion, in any federal or state court located in the County of New York, State of New York, USA, or, at Rightsholder's discretion, in any federal or state court whose geographical jurisdiction covers the location of the Rightsholder set forth in the Order Confirmation. The parties expressly submit to the personal jurisdiction and venue of each such federal or state court.</p> 
<p>If you have any comments or questions about these pay-per-use services or Copyright Clearance Center, please contact us at 978-750-8400 or send an e-mail to <a href="mailto:info@copyright.com".>info@copyright.com.</a></p>


</div>

