<META name="description" content="For uses traditionally reported under Copyright Clearance Center's (CCC) pay-per-use service to photocopy for general business use, library reserves, ILL/document delivery, etc., (formerly TRS), the applicable terms and conditions follow immediately below in Section A.">
<META name="author" content="Copyright Clearance Center">
<META name="keywords" content="Rights to Copy, Pay-per-use service, photocopy for general business use, photocopy for library reserves, photocopy for ill/document delivery, trs, dps, rls, terms and conditions">
<META name="rating" content="general">

<div>
	<b>Terms and Conditions for Permission Categories:  "Deliver via ILL or Document Delivery" and "Photocopy for General Business or Academic Use"</b>
<p>1. Scope of Authorization.</p> 
<p>You may reproduce chapters and articles from the publications included in CCC's pay-per-use service by reporting those copies and paying the rightsholders' fees through CCC. Reproduction by photocopy machine is covered by this pay-per-use system of authorizations, as is the facsimile transmission of copies ("faxing", "telecopying" or equivalent technology).</p>  
<p>2. Limitations on Use.</p> 
<p>Authorizations are limited (a) to the use of the person or entity reporting to CCC and (b) to the use of a specific customer of the person or entity reporting to CCC unless otherwise indicated in the permissions policy statement printed in the publication. Other limitations may be imposed by individual publications, as described in their own masthead or permission policy statements.</p> 
<p>3.  Uses expressly excluded: 
<UL>
<LI>electronic storage of any reproduction (whether in plain-text, PDF, or   any other format) other than on a transitory basis 
<LI>the input of works into computerized databases 
<LI>reproduction of an entire publication (cover-to-cover) 
<LI>reproduction for resale to anyone other than a specific customer 
<LI>republication in a different form</UL></p>
<p>Please obtain authorizations for these uses through other CCC services or directly from the rightsholder.</p>
<p>All rights not expressly granted are reserved; any license granted is further limited as set forth in any restrictions included in the Order Confirmation and/or in these terms and conditions.</p> 
<p>4. Copyright Rights.</p> 
<p>All Works and all rights therein, including copyright rights, remain the sole and exclusive property of the Rightsholder. The license created by the exchange of an Order Confirmation (and/or any invoice) and payment by User of the full amount set forth on that document includes only those rights expressly set forth in the Order Confirmation and in these terms and conditions, and conveys no other rights in the Work(s) to User.</p>
<p>5. Payment and Term.</p>  
<p>While User may exercise the rights licensed immediately upon issuance of the Order Confirmation, the license is automatically revoked and is null and void, as if it had never been issued, if complete payment for the license is not received on a timely basis either from User directly or through a payment agent, such as a credit card company. In the event that the material for which an electronic reproduction license is sought includes third party materials (such as photographs, illustrations, graphs and similar materials) which are identified as included in a Work by permission, such third party materials may not be reproduced except in the context of the Work. Unless otherwise provided in the Order Confirmation, any grant of rights to User (i) is "one-time", (ii) is non-exclusive and non-transferable, and (iii) is limited to one year all as measured from the "republication date" as identified in the Order Confirmation, if any, and otherwise from the date of the Order Confirmation. Upon completion of the licensed use, or at the end of the period identified in the previous sentence (if earlier), User shall immediately cease any new use of the Work(s) and shall destroy any further copies of the Work (except for copies printed on paper in accordance with this license and still in User's stock at the end of such period).</p> 
<p>6. Limitations on Use.</p> 
<p>User may not make or permit any alterations to the Work, unless expressly set forth in the Order Confirmation (after request by User and approval by Rightsholder). No Work may be used in any way that is defamatory, violates the rights of third parties (including such third parties' rights of copyright, privacy, publicity, or other tangible or intangible property), or is otherwise illegal, sexually explicit or obscene. In addition, User may not conjoin a Work with any other material that may result in damage to the reputation of the Rightsholder.</p> 
<p>7. Duty to Inform.</p> 
<p>User agrees to inform CCC if it becomes aware of any infringement of any rights in a Work and to cooperate with any reasonable request of CCC or the Rightsholder in connection therewith.</p> 
<p>8. Indemnification.</p> 
<p>User hereby indemnifies and agrees to defend the Rightsholder and CCC, and their respective employees and directors, against all claims, liability, damages, costs and expenses, including legal fees and expenses, arising out of any use of a Work beyond the scope of the rights granted herein, or any use of a Work which has been altered in any way by User, including claims of defamation or infringement of rights of copyright, publicity, privacy or other tangible or intangible property.</p> 
<p>9. LIMITATION OF LIABILITY.</p> 
<p>(a)	UNDER NO CIRCUMSTANCES WILL CCC OR THE RIGHTSHOLDER BE LIABLE FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES (INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF BUSINESS PROFITS OR INFORMATION, OR FOR BUSINESS INTERRUPTION) ARISING OUT OF THE USE OR INABILITY TO USE A WORK, EVEN IF ONE OF THEM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p> 
<p>(b)	IN ANY EVENT, THE TOTAL LIABILITY OF THE RIGHTSHOLDER AND CCC (INCLUDING THEIR RESPECTIVE EMPLOYEES AND DIRECTORS) SHALL NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY USER FOR THIS LICENSE. USER ASSUMES FULL LIABILITY FOR THE ACTIONS AND OMISSIONS OF ITS PRINCIPALS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS AND ASSIGNS.</P> 
<p>10. WARRANTIES; DISCLAIMERS.</p> 
<p>(a)	THE WORK(S) AND RIGHT(S) ARE PROVIDED "AS IS".  THE RIGHTSHOLDER(S) HAS GRANTED CCC THE RIGHT TO GRANT PERMISSION UNDER THESE PAY-PER-USE SERVICES, AND HAS WARRANTED THAT IT HAS ALL RIGHTS NECESSARY TO AUTHORIZE CCC TO ACT ON ITS BEHALF.  CCC AND THE RIGHTSHOLDER DISCLAIM ALL OTHER WARRANTIES RELATING TO THE WORK(S) AND RIGHT(S), EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. ADDITIONAL RIGHTS MAY BE REQUIRED TO USE PORTIONS OF THE WORK (AS OPPOSED TO THE ENTIRE WORK) IN A MANNER CONTEMPLATED BY USER; USER UNDERSTANDS AND AGREES THAT NEITHER CCC NOR THE RIGHTSHOLDER MAY HAVE SUCH ADDITIONAL RIGHTS TO GRANT.</p> 
<p>(b)	USER ACKNOWLEDGES THAT THE RIGHTS GRANTED HEREUNDER OR UNDER ANY ORDER CONFIRMATION DO NOT INCLUDE ANY MODEL, PROPERTY OR OTHER RELEASES WHICH MAY BE NECESSARY FOR CERTAIN USES OF WORKS CONSISTING OF OR CONTAINING PHOTOGRAPHS, OTHER STILL IMAGES OR AUDIOVISUAL CONTENT.  USER ACKNOWLEDGES THAT ADDITIONAL RIGHTS OR RELEASES MAY BE NECESSARY FOR CERTAIN USES OF MATERIALS WHICH INCLUDE DEPICTIONS OF PERSONS, PROPERTY OR TRADEMARKS AND THAT USER (AND NOT CCC OR ANY RIGHTSHOLDER) IS SOLELY RESPONSIBLE FOR OBTAINING ANY SUCH REQUIRED RIGHT OR RELEASE.</P>
<p>11. Miscellaneous</p>
      <p>11.1: Assignment or Transfer: The licensing transaction described in the Order Confirmation is personal to User. Therefore, User may not assign or transfer to any other person (whether a natural person or an organization of any kind) the license created by the Order Confirmation and these terms and conditions or any rights granted hereunder, subject to the following exception. The exception: in cases where a person is specifically engaged by a second person to provide reproductions of Works to (and/or to obtain licenses on behalf of) the second person and EITHER (i) the first person expressly notifies the second person of its obligation not to redistribute or otherwise use the material without authorization, OR (ii) the second person is identified in the Order Confirmation as the publisher of the material to include the Work licensed under this service, then the license may be transferred to the second person and both the first person and the second person shall be jointly deemed to be the "User" under the Order Confirmation and these terms and conditions for that transaction. An organizational User and its principals, employees, agents and affiliates are jointly and severally liable for the performance of all payments and other obligations hereunder.</p> 
      <p>11.2: Amendment or Waiver, Objection to Contrary Terms. No amendment or waiver of any terms is binding unless set forth in a writing other than a standard User or CCC form and signed by the parties. The Rightsholder and CCC hereby object to any terms contained in any writing prepared by the User or its principals, employees, agents or affiliates and purporting to govern or otherwise relate to the licensing transaction described in the Order Confirmation, which terms are in any way inconsistent with any terms set forth in the Order Confirmation and/or in these terms and conditions or CCC's standard operating procedures, whether such writing is prepared prior to, simultaneously with or subsequent to the Order Confirmation, and whether such writing appears on a copy of the Order Confirmation or in a separate instrument.</p> 
     <p>11.3: Effect of Breach.  Any failure by User to pay any amount when due, or any use by User of a Work beyond the scope of the license set forth in the Order Confirmation and/or these terms and conditions, shall be a material breach of the license created by the Order Confirmation and these terms and conditions. Any breach not cured within 10 days of notice thereof shall result in immediate termination of such license without further notice. Invoices are due and payable upon receipt. Any unauthorized (but licensable) use of a Work that is terminated immediately upon notice thereof may be liquidated by payment of the Rightsholder's ordinary license price therefore; any unauthorized (and unlicensable) use that is not terminated immediately for any reason (including, for example, because materials containing the Work cannot reasonably be recalled) will be subject to all remedies available at law or in equity, but in no event to a payment of less than three times the Rightsholder's ordinary license price for the most closely analogous licensable use plus Rightsholder's and/or CCC's costs and expenses incurred in collecting such payment.</p> 
     <p>11.4: Governing Law and Jurisdiction.  The licensing transaction described in the Order Confirmation document shall be governed by and construed under the law of the State of New York, USA, without regard to the principles thereof of conflicts of law. Any case, controversy, suit, action, or proceeding arising out of, in connection with, or related to such licensing transaction shall be brought, at CCC's sole discretion, in any federal or state court located in the County of New York, State of New York, USA, or in any federal or state court whose geographical jurisdiction covers the location of the Rightsholder set forth in the Order Confirmation. The parties expressly submit to the personal jurisdiction and venue of each such federal or state court.</p> 
<p>If you have any comments or questions about this pay-per-use service or Copyright Clearance Center, please contact us at 978-750-8400 or send an e-mail to <a href="mailto:info@copyright.com".>info@copyright.com.</a></p>

</div>






